### ISSUE TITLE
Investigate the usage of Optional<T> instead of null

### ISSUE THREAD

**Issue by stoewer** [G-Node/nix-java#27]
Investigate the advantages of using Java 8 `Optional<T>` instead of `null` in the public API of the bindings:

* Identify the places that need to be changed (where can `null` be used as an argument or can be expected as return value).
* What solution is nicer from the user perspective?

**Comment by sujithvm** [comment]
@stoewer Using Java 8 Optionals is a good but where all should it be changed?
The main scenarios where null is used are : 
1) Where values are optionals as obtained from NIX (eg. https://github.com/G-Node/nix-java/blob/master/src/main/java/org/gnode/nix/Block.java#L161 ) .
Such functions would benefit from Java 8 Optionals.

2) Returning null for uninitialized objects. (eg : https://github.com/G-Node/nix-java/blob/master/src/main/java/org/gnode/nix/Block.java#L180 )

3) Using null to clear value. (eg : https://github.com/G-Node/nix-java/blob/master/src/main/java/org/gnode/nix/Block.java#L180 )

I am not completely sure if using Optionals for scenario 2, 3 would be a good solution. 
What do you suggest? 
Thank you

**Comment by stoewer** [comment]
From my point of view the main advantage of `Optional` would be to implement a `null` free API. This means that, if we want to use `Optional` we should use for all 3 scenarios. However, the concept of `Optional` is still very new in the Java world, therefore I am not sure whether it is really nicer to use it. 

If it is OK for you I suggest that we just try it out for one class (e.g. `Block`) and see how it looks like and then decide whether we use it or not.

**Comment by sujithvm** [comment]
@stoewer This likely how Optionals would look 
1) https://github.com/sujithvm/nix-java/blob/issue27/src/main/java/org/gnode/nix/Block.java#L212 
2) https://github.com/sujithvm/nix-java/blob/issue27/src/main/java/org/gnode/nix/Block.java#L230) 
3) https://github.com/sujithvm/nix-java/blob/issue27/src/main/java/org/gnode/nix/Block.java#L196  

Test : https://github.com/sujithvm/nix-java/blob/issue27/src/test/java/org/gnode/nix/TestBlock.java#L71

I could not change for the entire class as it breaks other codes dependent on Block. If we decide to proceed with Optionals I will change them.

**Comment by stoewer** [comment]
Use of Optional postponed for now.
