### ISSUE TITLE
Bindings for util.hpp

### ISSUE THREAD

**Issue by sujithvm** [G-Node/nix-java#38]
Create bindings and tests for util/util.hpp .

**Comment by stoewer** [comment]
The functions in `util.hpp` are only used internally. Bindings to them are not necessary.

**Comment by jgrewe** [comment]
On 07/01/2015 08:05 AM, A. Stoewer wrote:
> The functions in |util.hpp| are only used internally. Bindings to them
> are not necessary.
> 
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/G-Node/nix-java/issues/38#issuecomment-117444451>.
> 
Hi @stoewer,

I'm not so sure, if binding for them would not be appreciated. e.g. the
units conversion function may come in handy. Imho, they certainly don't
have priority, but if there is time, I would not mind to have them...

best,
Jan

**Comment by stoewer** [comment]
@jgrewe Thanks for the feedback, I will reopen this issue
