### ISSUE TITLE
CppUnit annotations in method documentation

### ISSUE THREAD

**Issue by stoewer** [G-Node/nix-java#49]
In the [javadoc](http://g-node.github.io/nix-java/) all CppUnit annotations are shown in the signature.

```java
@Cast(value="bool")
public boolean deleteMultiTag(@Const @ByRef MultiTag multiTag)
```

From my point of view this may be a bit confusing for the user who does not know about CppUnit. Is there a way to skip annotations in the generated API doc? If yes, this would be much nicer.

**Comment by sujithvm** [comment]
@stoewer Is there a way to go about solving this? I could not find any direct JavaDoc configuration to achieve the same.

**Comment by stoewer** [comment]
OK. I'll close the issue
