### ISSUE TITLE
License must be changed

### ISSUE THREAD

**Issue by stoewer** [G-Node/nix-java#56]
See discussion here: https://github.com/G-Node/nix/issues/542

**Comment by stoewer** [comment]
@sujithvm We found out that our current license is incompatible with the GPL. Therefore we would like to change it (probably to the BSD 3-clause license). But of course we need your consent in order to do so. Please let me know whether you agree to the license change. If not, please voice your concerns here: https://github.com/G-Node/nix/issues/542

**Comment by sujithvm** [comment]
@stoewer I have no objections. Thank you
