### ISSUE TITLE
Optimize bindings

### ISSUE THREAD

**Issue by stoewer** [G-Node/nix-java#9]
Optimize and refactor the existing bindings:
* Optimize the build process
* Make use of base classes for `Block` and `File`
* Throw nicer exceptions etc
* Implement `equals()`, `hasCode()` and `compareTo()`

**Comment by sujithvm** [comment]
@stoewer On what parameters/fields should `equals()` , `hashCode()` and `compareTo()` be implemented. For Block we can use id, name, type and which other fields? For file what all fields can be considered? Thank you

**Comment by stoewer** [comment]
Most NIX entities have a unique `id`, therefore `hashCode()` and `equals()` can be implemented using this id. For `File` this is not so easy, since `location` can be the relative path of the file it can't be used for this purpose. `File` has an `operator==()` but the downside here is that it can only be used to implement `equals()` but not for a consistent `hashCode()` method. Maybe just skip both methods for `File` for now, I will give it some thoughts...  

Compare to should work on a human readable identifier such as `name` for `Block` or `location` for `File`.
